SET IDENTITY_INSERT tblSystemAccountCodes ON

INSERT INTO tblSystemAccountCodes(Id, Code, Name, Active)
SELECT 1, 'ACCOUNTS PAYABLE', 'ACCOUNTS PAYABLE', 1
	UNION ALL
SELECT 2, 'ACCOUNTS RECEIVABLE', 'ACCOUNTS RECEIVABLE', 1
	UNION ALL
SELECT 3, 'INPUT VAT', 'INPUT VAT', 1
	UNION ALL
SELECT 4, 'OUTPUT VAT', 'OUTPUT VAT', 1

SET IDENTITY_INSERT tblSystemAccountCodes OFF
GO

