IF OBJECT_ID('tblVATTypes') IS NULL
	CREATE TABLE tblVATTypes(
		Id INT IDENTITY(1, 1) NOT NULL,
		Code VARCHAR(50) NOT NULL,
		Name VARCHAR(100) NULL,
		Rate MONEY NOT NULL,
		Active BIT NOT NULL CONSTRAINT DF_tblVATTypes_Active DEFAULT 1,
	)
GO

IF OBJECT_ID('tblVATTypes_PK') IS NOT NULL
	ALTER TABLE tblVATTypes DROP CONSTRAINT tblVATTypes_PK
GO

ALTER TABLE tblVATTypes ADD CONSTRAINT tblVATTypes_PK PRIMARY KEY(Id)
GO

