IF OBJECT_ID('tblItems') IS NULL
	CREATE TABLE tblItems(
		Id INT IDENTITY(1, 1) NOT NULL,
		CompanyId INT NOT NULL,
		Code VARCHAR(50) NOT NULL,
		Name VARCHAR(100) NULL,
		Remarks VARCHAR(1000) NULL,
		Active BIT NOT NULL CONSTRAINT DF_tblItems_Active DEFAULT 1,
		CreatedById INT NOT NULL,
		DateCreated DATETIME NOT NULL,
		ModifiedById INT NOT NULL,
		DateModified DATETIME NOT NULL,
	)
GO

IF OBJECT_ID('tblItems_PK') IS NOT NULL
	ALTER TABLE tblItems DROP CONSTRAINT tblItems_PK
GO

ALTER TABLE tblItems ADD CONSTRAINT tblItems_PK PRIMARY KEY(Id)
GO

