IF OBJECT_ID('tblMonths') IS NULL
	CREATE TABLE tblMonths(
		Id INT IDENTITY(1, 1) NOT NULL,
		Name VARCHAR(100) NOT NULL,
	)
GO

IF OBJECT_ID('tblMonths_PK') IS NOT NULL
	ALTER TABLE tblMonths DROP CONSTRAINT tblMonths_PK
GO

ALTER TABLE tblMonths ADD CONSTRAINT tblMonths_PK PRIMARY KEY(Id)
GO

